### ISSUE TITLE
Unable to select a folder for creating the very first graph

### ISSUE THREAD

**Issue by yudistrange** [flathub/com.logseq.Logseq#33]
On launching LogSeq it shows a tutorial graph. It then asks to select a folder to create a new graph at the end of the tutorial.

However I am unable to select a folder to start a new graph. The application does nothing and takes me back to the select folder screen.

Relevant Logs:
```
flatpak run com.logseq.Logseq
F: Can't get document portal: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Remote peer disconnected
[3 zypak-helper] Wait found events, but sd-event found none
LaunchProcess: failed to execvp:
xdg-settings
[3:1129/120207.159028:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:1129/120207.159072:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
LaunchProcess: failed to execvp:
xdg-settings
12:02:07.192 › Logseq App(0.8.11) Starting... 
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[52:1129/120208.750948:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
12:02:09.023 › :electron.handler/watch-dir {:path "/home/udit/.logseq/config"}
12:02:09.067 › :electron.handler/unwatch-dir {:path "/local"}
12:02:09.068 › :electron.handler/watch-dir {:path "/local"}
[3:1129/120210.117186:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:1129/120210.117222:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:1129/120210.117258:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:1129/120210.117280:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:1129/120210.117299:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
12:02:11.382 › :electron.handler/open-dir open folder selection dialog
12:02:13.357 › :electron.handler/open-dir {:path nil}
Error occurred in handler for 'main': Error: path empty
    at /app/logseq/resources/app/electron.js:14111:334
    at Function.$G__96157__1$$ [as $cljs$core$IFn$_invoke$arity$1$] (/app/logseq/resources/app/electron.js:4013:173)
    at /app/logseq/resources/app/electron.js:13161:80
    at async node:electron/js2c/browser_init:189:563
```

This issue only occurs if I install logseq via flatpak. I compiled the application from source and it was able to access disk for creating a new graph.
Also worth noting that once it worked with the compiled app, it started working with the flatpak installed app as well.

I added an [issue on the logseq repo](https://github.com/logseq/logseq/issues/7507), I was redirected here. It seems like flatpak installation is not getting correct permissions.

**Comment by kanru** [comment]
Hi, were you trying to open a directory outside of the $HOME dir?

The default permission of the flatpak only allows the app to access files inside $HOME. If you need you can use the [Flatseal](https://flathub.org/apps/details/com.github.tchx84.Flatseal) tool to adjust the permissions.

**Comment by yudistrange** [comment]
@kanru no it was an empty subdirectory in my $HOME dir

**Comment by kanru** [comment]
I see. Could you share your distro and desktop environment version?

> 12:02:09.023 › :electron.handler/watch-dir {:path "/home/udit/.logseq/config"}
> 12:02:09.067 › :electron.handler/unwatch-dir {:path "/local"}
> 12:02:09.068 › :electron.handler/watch-dir {:path "/local"}

The last two lines shows Logseq was trying to open a folder under root filesystem. It might be a symbolic link in your $HOME but actually was pointing to the root. It could be possible some distro has this kind of setup by default.

**Comment by yudistrange** [comment]
I am using fedora-37 server edition, with sway-1.7 as the desktop compositor for wayland
It is a bare-bones installation, so I might have some things missing, but then the installation should prompt / fail for them, right?

**Comment by kanru** [comment]
Yes, I agree this is unexpected.

I think there are two bugs

1. Logseq should warn when it doesn't have permission to open a directory
2. I'm using fedora-37 silverblue as well. I don't remember the default installation has a `/local` dir

I'll try to reproduce both issues. Did you follow any guide to setup your bare-bone installation?

**Comment by kanru** [comment]
I can reproduce similar error message by either

```bash
ln -s /mnt $HOME/local
```

or

```bash
mkdir $HOME/local
chmod a-rwx $HOME/local
```

And then try to open the `$HOME/local` folder

**Comment by yudistrange** [comment]
> Did you follow any guide to setup your bare-bone installation?

Nope. Just installed fedora-37 server edition. Then installed sway (which brought in display deps)

**Comment by almereyda** [comment]
The upstream issue is closed, and the fix from https://github.com/logseq/logseq/pull/8200 was included with https://github.com/logseq/logseq/commit/2e374f7b0895772c924c3d8afc4815fa9460c2fe in the 0.8.17 release.

Is this eventually fixed for the Flatpak as well?

**Comment by kanru** [comment]
The upstream issue is fixed, accessing folders without sufficient permission will show an error.

I also tested opening a folder symlinked to home and it seems to work.

```
sudo mkdir /mnt/TestNotes
sudo chown kanru:kanru /mnt/TestNotes
cd $HOME && ln -s /mnt/TestNotes
```

When opened in Logseq it shows the sandboxed user folder, but the rest works fine

```
All graphs

Local graphs:

b2088959/TmpNotes             Unlink

[Open a local directory]
```

**Comment by M-Pixel** [comment]
I'm running into this as well, on RHEL 9.6 atomic edition.  The behavior happens even when selecting directories under `.var/app/com.logseq.Logseq/config` which Logseq has itself created.  I suspected the home symlink might be an issue, but the same happens when I try to open `/var/graph` which I created, put all-rw permissions on, and gave Logseq full filesystem permissions through flatpak.  Perhaps there's something simpler going on, like using the wrong member name for the result of the filesystem picker and thus getting "nil" no matter which path (valid or not, permissions or not) the user picks.
