### ISSUE TITLE
Flatpak-specific logseq crash on file upload with non-ASCII symbols in file name

### ISSUE THREAD

**Issue by rominf** [flathub/com.logseq.Logseq#9]
### Steps to reproduce

1. Open logseq, installed using Flatpak (0.6.8, latest version ATM).
2. Type in editor `/Upload an asset` and select the first item.
3. Select the file with a non-ASCII symbol in a filename like: `ö.txt` (can be empty, PDF, etc., it doesn't matter).
4. Observe the crash.
5. Repeat same steps using logseq, installed using AppImage. Observe no crashes.

### System info
openSUSE Tumbleweed with updates installed

**Comment by kanru** [comment]
Hmm. I can't reproduce this on my side.

Can you run `flatpak run com.logseq.Logseq` from console and see if there's any interesting logs?

**Comment by rominf** [comment]
Sure:
```
$ flatpak run com.logseq.Logseq                                                                     Пт 20 мая 2022 21:45:15
LaunchProcess: failed to execvp:
xdg-settings
Gtk-Message: 21:45:22.814: Failed to load module "canberra-gtk-module"
[3:0520/214522.869745:ERROR:bus.cc(392)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
LaunchProcess: failed to execvp:
xdg-settings
21:45:22.980 › Logseq App(0.6.8) Starting...
[48:0520/214523.022064:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
[3:0520/214553.097951:ERROR:browser_main_loop.cc(269)] GLib-GObject: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
[3:0520/214553.802746:ERROR:browser_main_loop.cc(269)] GLib-GObject: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
[3:0520/214554.198659:ERROR:browser_main_loop.cc(269)] GLib-GObject: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
[3:0520/214557.543411:ERROR:browser_main_loop.cc(269)] GLib-GObject: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
[3:0520/214620.003784:ERROR:bad_message.cc(29)] Terminating renderer for bad IPC message, reason 2
uncaughtException Error: Render frame was disposed before WebFrameMain could be accessed
    at Object.n.send (node:electron/js2c/browser_init:169:413)
    at Object.b.send (node:electron/js2c/browser_init:165:2492)
    at BrowserWindow.<anonymous> (/app/logseq/resources/app/electron.js:12681:37)
    at BrowserWindow.emit (node:events:394:28)
node:electron/js2c/browser_init:169
/*! no static exports found */function(e,t,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0});const o=r(/*! @electron/internal/browser/message-port-main */"./lib/browser/message-port-main.ts"),{WebFrameMain:n,fromId:s}=process._linkedBinding("electron_browser_web_frame_main");n.prototype.send=function(e,...t){if("string"!=typeof e)throw new Error("Missing required channel argument");return this._send(!1,e,t)},n.prototype._sendInternal=function(e,...t){if("string"!=typeof e)throw new Error("Missing required channel argument");return this._send(!0,e,t)},n.prototype.postMessage=function(...e){Array.isArray(e[2])&&(e[2]=e[2].map(e=>e instanceof o.MessagePortMain?e._internalPort:e)),this._postMessage(...e)},t.default={fromId:s}},"./lib/browser/default-menu.ts":
                                                                                                                                                                                                                                                                                                                                                                                                                            ^

Error: Render frame was disposed before WebFrameMain could be accessed
    at Object.n.send (node:electron/js2c/browser_init:169:413)
    at Object.b.send (node:electron/js2c/browser_init:165:2492)
    at $electron$utils$send_to_renderer$cljs$0core$0IFn$0_invoke$0arity$03$$ (/app/logseq/resources/app/electron.js:11756:83)
    at $electron$utils$send_to_renderer$cljs$0core$0IFn$0_invoke$0arity$02$$ (/app/logseq/resources/app/electron.js:11753:10)
    at process.$electron$exceptions$app_uncaught_handler$$ (/app/logseq/resources/app/electron.js:14534:3)
    at process.emit (node:events:406:35)
    at process._fatalException (node:internal/process/execution:170:25)
```

**Comment by kanru** [comment]
Thanks.

I can reproduce with non en_US locale.

To reproduce I need to run

```
$ LC_ALL=ja_JP.UTF-8 flatpak com.logseq.Logseq
```

**Comment by kanru** [comment]
It looks like this error happens when the expected locale is not installed.

For example my default locale in Flatpak is

```
$ flatpak config
languages: *unset* (default: en)
extra-languages: *unset*
```

To install the `jp` locale I need to run

```
$ flatpak config --set extra-languages ja
$ flatpak update
Looking for updates…


        ID                                                Branch            Op            Remote            Download
 1. [✓] com.logseq.Logseq.Locale                          stable            u             flathub             1.0 kB / 59.9 kB
 2. [✓] com.transmissionbt.Transmission.Locale            stable            u             flathub            18.5 kB / 962.7 kB
 3. [✓] md.obsidian.Obsidian.Locale                       stable            u             flathub             1.0 kB / 3.2 MB
 4. [✓] org.chromium.Chromium.Locale                      stable            u             flathub             1.0 kB / 112.8 kB
 5. [✓] org.freedesktop.Platform.Locale                   20.08             u             flathub             1.6 MB / 322.3 MB
 6. [✓] org.freedesktop.Platform.Locale                   21.08             u             flathub           817.2 kB / 325.8 MB
 7. [✓] org.electronjs.Electron2.BaseApp                  21.08             u             flathub             2.5 kB / 1.1 MB
 8. [✓] org.freedesktop.Sdk.Locale                        20.08             u             flathub            53.7 kB / 327.1 MB
 9. [✓] org.freedesktop.Sdk.Locale                        21.08             u             flathub            33.5 kB / 330.8 MB
10. [✓] org.gnome.Platform.Locale                         41                u             flathub           151.7 kB / 336.6 MB
11. [✓] org.gnome.Platform.Locale                         42                u             flathub            10.9 kB / 336.0 MB
12. [✓] org.inkscape.Inkscape.Locale                      stable            u             flathub           332.4 kB / 14.3 MB
13. [✓] org.mozilla.firefox.Locale                        stable            u             flathub           538.3 kB / 46.5 MB
```

Then running Logseq with the non-en_US locale will not crash.

**Comment by rominf** [comment]
I can confirm that it works now. I didn't know about this command. Thanks.
